### ISSUE TITLE
Errors  in using these configurations

### ISSUE THREAD

**Issue by Azizaman** [pytholic/pytholic-lvim#1]
I am new to the vim and I copy and pasted your lvim configurations but it is showing erros do I have to install some packages before running them or what should I do to run the confs properly please help

**Comment by pytholic** [comment]
@Azizaman can you show me the errors?

**Comment by Azizaman** [comment]
yeah sure
![image](https://github.com/pytholic/pytholic-lvim/assets/110014054/72cb423f-364a-44e1-bc71-ff1bc0dc9c05)
i dont know what to do .

**Comment by Azizaman** [comment]
![image](https://github.com/pytholic/pytholic-lvim/assets/110014054/9f72cddc-7cae-4a28-8c13-d28356148fdf)

**Comment by pytholic** [comment]
@Azizaman 
Install clang with Mason. 
https://github.com/williamboman/mason.nvim#commands

Also run `:TSUpdate`.
https://github.com/LunarVim/LunarVim/issues/3460

**Comment by Azizaman** [comment]
thanks man now its running good .do u still use these configurations or u have changed.

**Comment by pytholic** [comment]
@Azizaman Glad it worked.
Now I use `Vim` only for minor editing. I use `VS Code` with the [VSpaceCode](https://vspacecode.github.io/) extension. I had to switch mainly because of `C++` stuff. Vim was hard to use for running `CMake` stuff and C++ programs, especially the debugging parts.
